let g:tex_seven#omniMath#symbols = [
      \ {"word":  "\\aleph",               "menu":  "ℵ "},
      \ {"word":  "\\alpha",               "menu":  "α "},
      \ {"word":  "\\amalg",               "menu":  "⨿ "},
      \ {"word":  "\\angle",               "menu":  "∠ "},
      \ {"word":  "\\approx",              "menu":  "≈ "},
      \ {"word":  "\\approxeq",            "menu":  "≊ "},
      \ {"word":  "\\ast",                 "menu":  "∗ "},
      \ {"word":  "\\asymp",               "menu":  "≍ "},
      \ {"word":  "\\backepsilon",         "menu":  "϶ "},
      \ {"word":  "\\backsim",             "menu":  "∽ "},
      \ {"word":  "\\backsimeq",           "menu":  "⋍ "},
      \ {"word":  "\\backslash",           "menu":  "\\"},
      \ {"word":  "\\because",             "menu":  "∵ "},
      \ {"word":  "\\beta",                "menu":  "β "},
      \ {"word":  "\\between",             "menu":  "≬ "},
      \ {"word":  "\\bigcap",              "menu":  "∩ "},
      \ {"word":  "\\bigcirc",             "menu":  "◦ "},
      \ {"word":  "\\bigcup",              "menu":  "∪ "},
      \ {"word":  "\\bigodot",             "menu":  "⊙ "},
      \ {"word":  "\\bigoplus",            "menu":  "⊕ "},
      \ {"word":  "\\bigotimes",           "menu":  "⊗ "},
      \ {"word":  "\\bigsqcup",            "menu":  "⊔ "},
      \ {"word":  "\\bigtriangledown",     "menu":  "▽ "},
      \ {"word":  "\\bigtriangleup",       "menu":  "△ "},
      \ {"word":  "\\biguplus",            "menu":  "⊎ "},
      \ {"word":  "\\bigvee",              "menu":  "∨ "},
      \ {"word":  "\\bigwedge",            "menu":  "∧ "},
      \ {"word":  "\\blacktriangleleft",   "menu":  "◂"},
      \ {"word":  "\\blacktriangleright",  "menu":  "▸"},
      \ {"word":  "\\bot",                 "menu":  "⊥ "},
      \ {"word":  "\\bowtie",              "menu":  "▷◁ "},
      \ {"word":  "\\Box",                 "menu":  "□ "},
      \ {"word":  "\\bullet",              "menu":  "• "},
      \ {"word":  "\\Bumpeq",              "menu":  "≎ "},
      \ {"word":  "\\bumpeq",              "menu":  "≏ "},
      \ {"word":  "\\cap",                 "menu":  "∩ "},
      \ {"word":  "\\cdot",                "menu":  "·"},
      \ {"word":  "\\cdots",               "menu":  "···"},
      \ {"word":  "\\chi",                 "menu":  "χ "},
      \ {"word":  "\\circ",                "menu":  "◦ "},
      \ {"word":  "\\circeq",              "menu":  "≗ "},
      \ {"word":  "\\clubsuit",            "menu":  "♣ "},
      \ {"word":  "\\cong",                "menu":  "≅ "},
      \ {"word":  "\\coprod",              "menu":  "⨿ "},
      \ {"word":  "\\cup",                 "menu":  "∪ "},
      \ {"word":  "\\curlyeqprec",         "menu":  "⋞  "},
      \ {"word":  "\\curlyeqsucc",         "menu":  "⋟  "},
      \ {"word":  "\\dagger",              "menu":  "† "},
      \ {"word":  "\\dashv",               "menu":  "⊣ "},
      \ {"word":  "\\ddagger",             "menu":  "‡ "},
      \ {"word":  "\\ddots",               "menu":  "..."},
      \ {"word":  "\\Delta",               "menu":  "∆ "},
      \ {"word":  "\\delta",               "menu":  "δ "},
      \ {"word":  "\\diamond",             "menu":  "⋄ "},
      \ {"word":  "\\Diamond",             "menu":  "♢ "},
      \ {"word":  "\\diamondsuit",         "menu":  "♢ "},
      \ {"word":  "\\div",                 "menu":  "÷ "},
      \ {"word":  "\\doteq",               "menu":  "≐ "},
      \ {"word":  "\\dots",                "menu":  "… "},
      \ {"word":  "\\downarrow",           "menu":  "↓ "},
      \ {"word":  "\\Downarrow",           "menu":  "⇓ "},
      \ {"word":  "\\doteqdot",            "menu":  "≑ "},
      \ {"word":  "\\ell",                 "menu":  "ℓ "},
      \ {"word":  "\\emptyset",            "menu":  "∅ "},
      \ {"word":  "\\epsilon",             "menu":  "ϵ "},
      \ {"word":  "\\eqcirc",              "menu":  "≖ "},
      \ {"word":  "\\equiv",               "menu":  "≡ "},
      \ {"word":  "\\eqslantgtr",          "menu":  "⪖ "},
      \ {"word":  "\\eqslantless",         "menu":  "⪕ "},
      \ {"word":  "\\eta",                 "menu":  "η "},
      \ {"word":  "\\exists",              "menu":  "∃ "},
      \ {"word":  "\\fallingdotseq",       "menu":  "≒ "},
      \ {"word":  "\\flat",                "menu":  "♭ "},
      \ {"word":  "\\forall",              "menu":  "∀ "},
      \ {"word":  "\\frown",               "menu":  "⌢ "},
      \ {"word":  "\\gamma",               "menu":  "γ "},
      \ {"word":  "\\Gamma",               "menu":  "Γ "},
      \ {"word":  "\\geq",                 "menu":  "≥ "},
      \ {"word":  "\\geqq",                "menu":  "≧ "},
      \ {"word":  "\\geqslant",            "menu":  "⩾ "},
      \ {"word":  "\\gets",                "menu":  "← "},
      \ {"word":  "\\gg",                  "menu":  "≫ "},
      \ {"word":  "\\ggg",                 "menu":  "⋙  "},
      \ {"word":  "\\gtrapprox",           "menu":  "⪆ "},
      \ {"word":  "\\gtrdot",              "menu":  "NC"},
      \ {"word":  "\\gtreqless",           "menu":  "⋛ "},
      \ {"word":  "\\gtreqqless",          "menu":  "⪌ "},
      \ {"word":  "\\gtrless",             "menu":  "≷ "},
      \ {"word":  "\\gtrsim",              "menu":  "≳ "},
      \ {"word":  "\\hbar",                "menu":  "ħ "},
      \ {"word":  "\\heartsuit",           "menu":  "♡ "},
      \ {"word":  "\\hookleftarrow",       "menu":  "↩ "},
      \ {"word":  "\\hookrightarrow",      "menu":  "↪ "},
      \ {"word":  "\\imath",               "menu":  "ı "},
      \ {"word":  "\\Im",                  "menu":  "ℑ "},
      \ {"word":  "\\iff",                 "menu":  "⇐⇒ "},
      \ {"word":  "\\infty",               "menu":  "∞ "},
      \ {"word":  "\\in",                  "menu":  "∈ "},
      \ {"word":  "\\int",                 "menu":  "∫ "},
      \ {"word":  "\\iota",                "menu":  "ι "},
      \ {"word":  "\\jmath",               "menu":  "ȷ "},
      \ {"word":  "\\kappa",               "menu":  "κ "},
      \ {"word":  "\\lambda",              "menu":  "λ "},
      \ {"word":  "\\Lambda",              "menu":  "Λ "},
      \ {"word":  "\\land",                "menu":  "∧ "},
      \ {"word":  "\\langle",              "menu":  "〈"},
      \ {"word":  "\\lceil",               "menu":  "⌈"},
      \ {"word":  "\\ldots",               "menu":  "..."},
      \ {"word":  "\\leadsto",             "menu":  "⇝ "},
      \ {"word":  "\\leftarrow",           "menu":  "← "},
      \ {"word":  "\\Leftarrow",           "menu":  "⇐ "},
      \ {"word":  "\\leftharpoondown",     "menu":  "↽ "},
      \ {"word":  "\\leftharpoonup",       "menu":  "↼ "},
      \ {"word":  "\\leftrightarrow",      "menu":  "↔ "},
      \ {"word":  "\\Leftrightarrow",      "menu":  "⇔ "},
      \ {"word":  "\\leq",                 "menu":  "≤ "},
      \ {"word":  "\\leqq",                "menu":  "≦ "},
      \ {"word":  "\\leqslant",            "menu":  "⩽ "},
      \ {"word":  "\\lessapprox",          "menu":  "⪅ "},
      \ {"word":  "\\lessdot",             "menu":  "NC"},
      \ {"word":  "\\lesseqgtr",           "menu":  "⋚ "},
      \ {"word":  "\\lesseqqgtr",          "menu":  "⪋ "},
      \ {"word":  "\\lessgtr",             "menu":  "≶ "},
      \ {"word":  "\\lesssim",             "menu":  "≲ "},
      \ {"word":  "\\lfloor",              "menu":  "⌊ "},
      \ {"word":  "\\lhd",                 "menu":  "◁ "},
      \ {"word":  "\\ll",                  "menu":  "≪ "},
      \ {"word":  "\\lll",                 "menu":  "⋘  "},
      \ {"word":  "\\llcorner",            "menu":  "⌞ "},
      \ {"word":  "\\lnot",                "menu":  "¬ "},
      \ {"word":  "\\longleftarrow",       "menu":  "←− "},
      \ {"word":  "\\Longleftarrow",       "menu":  "⇐= "},
      \ {"word":  "\\longleftrightarrow",  "menu":  "←→ "},
      \ {"word":  "\\Longleftrightarrow",  "menu":  "⇐⇒ "},
      \ {"word":  "\\longmapsto",          "menu":  "−→ "},
      \ {"word":  "\\longrightarrow",      "menu":  "−→ "},
      \ {"word":  "\\Longrightarrow",      "menu":  "=⇒ "},
      \ {"word":  "\\lor",                 "menu":  "∨ "},
      \ {"word":  "\\lrcorner",            "menu":  "⌟ "},
      \ {"word":  "\\lVert",               "menu":  "‖ "},
      \ {"word":  "\\lvert",               "menu":  "| "},
      \ {"word":  "\\mapsto",              "menu":  "↦ "},
      \ {"word":  "\\|",                   "menu":  "∥ "},
      \ {"word":  "\\mho",                 "menu":  "℧ "},
      \ {"word":  "\\mid",                 "menu":  "| "},
      \ {"word":  "\\models",              "menu":  "⊧ "},
      \ {"word":  "\\mp",                  "menu":  "∓ "},
      \ {"word":  "\\mu",                  "menu":  "μ "},
      \ {"word":  "\\nabla",               "menu":  "∇ "},
      \ {"word":  "\\natural",             "menu":  "♮ "},
      \ {"word":  "\\nearrow",             "menu":  "↗ "},
      \ {"word":  "\\neg",                 "menu":  "¬ "},
      \ {"word":  "\\neq",                 "menu":  "≠ "},
      \ {"word":  "\\ni",                  "menu":  "∋ "},
      \ {"word":  "\\notin",               "menu":  "∉ "},
      \ {"word":  "\\nu",                  "menu":  "ν "},
      \ {"word":  "\\nwarrow",             "menu":  "↖ "},
      \ {"word":  "\\odot",                "menu":  "⊙ "},
      \ {"word":  "\\oint",                "menu":  "∮ "},
      \ {"word":  "\\omega",               "menu":  "ω "},
      \ {"word":  "\\Omega",               "menu":  "Ω "},
      \ {"word":  "\\ominus",              "menu":  "⊖ "},
      \ {"word":  "\\oplus",               "menu":  "⊕ "},
      \ {"word":  "\\oslash",              "menu":  "⊘ "},
      \ {"word":  "\\otimes",              "menu":  "⊗ "},
      \ {"word":  "\\owns",                "menu":  "∋ "},
      \ {"word":  "\\parallel",            "menu":  "∥"},
      \ {"word":  "\\partial",             "menu":  "∂"},
      \ {"word":  "\\perp",                "menu":  "⊥ "},
      \ {"word":  "\\Phi",                 "menu":  "Φ "},
      \ {"word":  "\\phi",                 "menu":  "ϕ "},
      \ {"word":  "\\Pi",                  "menu":  "Π "},
      \ {"word":  "\\pi",                  "menu":  "π "},
      \ {"word":  "\\pitchfork",           "menu":  "⋔ "},
      \ {"word":  "\\pm",                  "menu":  "± "},
      \ {"word":  "\\preceq",              "menu":  "⪯ "},
      \ {"word":  "\\prec",                "menu":  "≺ "},
      \ {"word":  "\\precapprox",          "menu":  "⪷ "},
      \ {"word":  "\\preccurlyeq",         "menu":  "≼  "},
      \ {"word":  "\\precsim",             "menu":  "≾ "},
      \ {"word":  "\\succsim",             "menu":  "≿ "},
      \ {"word":  "\\prime",               "menu":  "′ "},
      \ {"word":  "\\prod",                "menu":  "∏ "},
      \ {"word":  "\\propto",              "menu":  "∝ "},
      \ {"word":  "\\psi",                 "menu":  "ψ "},
      \ {"word":  "\\Psi",                 "menu":  "Ψ "},
      \ {"word":  "\\rangle",              "menu":  "〉"},
      \ {"word":  "\\rceil",               "menu":  "⌉"},
      \ {"word":  "\\Re",                  "menu":  "ℜ "},
      \ {"word":  "\\rfloor",              "menu":  "⌋ "},
      \ {"word":  "\\rhd",                 "menu":  "▷ "},
      \ {"word":  "\\rho",                 "menu":  "ρ "},
      \ {"word":  "\\rightarrow",          "menu":  "→ "},
      \ {"word":  "\\Rightarrow",          "menu":  "⇒ "},
      \ {"word":  "\\rightharpoondown",    "menu":  "⇁ "},
      \ {"word":  "\\rightharpoonup",      "menu":  "⇀ "},
      \ {"word":  "\\rightleftharpoons",   "menu":  "⇌ "},
      \ {"word":  "\\risingdotseq",        "menu":  "≓ "},
      \ {"word":  "\\rVert",               "menu":  "‖"},
      \ {"word":  "\\rvert",               "menu":  "|"},
      \ {"word":  "\\searrow",             "menu":  "↘ "},
      \ {"word":  "\\setminus",            "menu":  "\\"},
      \ {"word":  "\\sharp",               "menu":  "♯"},
      \ {"word":  "\\shortmid",            "menu":  "NC "},
      \ {"word":  "\\shortparallel",       "menu":  "NC "},
      \ {"word":  "\\sigma",               "menu":  "σ"},
      \ {"word":  "\\Sigma",               "menu":  "Σ"},
      \ {"word":  "\\simeq",               "menu":  "≃ "},
      \ {"word":  "\\sim",                 "menu":  "∼ "},
      \ {"word":  "\\smallfrown",          "menu":  "⌢ "},
      \ {"word":  "\\smile",               "menu":  "⌣"},
      \ {"word":  "\\spadesuit",           "menu":  "♠ "},
      \ {"word":  "\\sqcap",               "menu":  "⊓ "},
      \ {"word":  "\\sqcup",               "menu":  "⊔ "},
      \ {"word":  "\\sqsubseteq",          "menu":  "⊑ "},
      \ {"word":  "\\sqsubset",            "menu":  "⊏ "},
      \ {"word":  "\\sqsupseteq",          "menu":  "⊒ "},
      \ {"word":  "\\sqsupset",            "menu":  "⊐ "},
      \ {"word":  "\\star",                "menu":  "⋆ "},
      \ {"word":  "\\subseteq",            "menu":  "⊆ "},
      \ {"word":  "\\subseteqq",           "menu":  "⫅ "},
      \ {"word":  "\\Subset",              "menu":  "⋐ "},
      \ {"word":  "\\subset",              "menu":  "⊂ "},
      \ {"word":  "\\succeq",              "menu":  "⪰ "},
      \ {"word":  "\\succ",                "menu":  "≻ "},
      \ {"word":  "\\succapprox",          "menu":  "⪸ "},
      \ {"word":  "\\succcurlyeq",         "menu":  "≽  "},
      \ {"word":  "\\sum",                 "menu":  "∑ "},
      \ {"word":  "\\supseteq",            "menu":  "⊇ "},
      \ {"word":  "\\supseteqq",           "menu":  "⫆ "},
      \ {"word":  "\\Supset",              "menu":  "⋑ "},
      \ {"word":  "\\supset",              "menu":  "⊃ "},
      \ {"word":  "\\surd",                "menu":  "√ "},
      \ {"word":  "\\swarrow",             "menu":  "↙ "},
      \ {"word":  "\\tau",                 "menu":  "τ "},
      \ {"word":  "\\therefore",           "menu":  "∴ "},
      \ {"word":  "\\theta",               "menu":  "θ "},
      \ {"word":  "\\Theta",               "menu":  "Θ "},
      \ {"word":  "\\thickapprox",         "menu":  "≈ "},
      \ {"word":  "\\thicksim",            "menu":  "∼ "},
      \ {"word":  "\\times",               "menu":  "× "},
      \ {"word":  "\\to",                  "menu":  "→ "},
      \ {"word":  "\\top",                 "menu":  "⊤ "},
      \ {"word":  "\\triangle",            "menu":  "△ "},
      \ {"word":  "\\triangleleft",        "menu":  "◁ "},
      \ {"word":  "\\triangleright",       "menu":  "▷ "},
      \ {"word":  "\\triangleq",           "menu":  "≜ "},
      \ {"word":  "\\ulcorner",            "menu":  "⌜ "},
      \ {"word":  "\\unlhd",               "menu":  "⊴ "},
      \ {"word":  "\\unrhd",               "menu":  "⊵ "},
      \ {"word":  "\\uparrow",             "menu":  "↑ "},
      \ {"word":  "\\Uparrow",             "menu":  "⇑ "},
      \ {"word":  "\\updownarrow",         "menu":  "↕ "},
      \ {"word":  "\\Updownarrow",         "menu":  "⇕ "},
      \ {"word":  "\\uplus",               "menu":  "⊎ "},
      \ {"word":  "\\upsilon",             "menu":  "υ "},
      \ {"word":  "\\Upsilon",             "menu":  "Υ "},
      \ {"word":  "\\urcorner",            "menu":  "⌝ "},
      \ {"word":  "\\varnothing",          "menu":  "∅ "},
      \ {"word":  "\\varepsilon",          "menu":  "ε "},
      \ {"word":  "\\varphi",              "menu":  "φ "},
      \ {"word":  "\\varpi",               "menu":  "ϖ "},
      \ {"word":  "\\varpropto",           "menu":  "∝ "},
      \ {"word":  "\\varrho",              "menu":  "ϱ "},
      \ {"word":  "\\varsigma",            "menu":  "ς "},
      \ {"word":  "\\vartheta",            "menu":  "ϑ "},
      \ {"word":  "\\vartriangleleft",     "menu":  "◃ "},
      \ {"word":  "\\vartriangleright",    "menu":  "▹"},
      \ {"word":  "\\Vdash",               "menu":  "⊩ "},
      \ {"word":  "\\vDash",               "menu":  "⊨ "},
      \ {"word":  "\\vdash",               "menu":  "⊢ "},
      \ {"word":  "\\vdots",               "menu":  "..."},
      \ {"word":  "\\vee",                 "menu":  "∨"},
      \ {"word":  "\\Vert",                "menu":  "‖"},
      \ {"word":  "\\vert",                "menu":  "|"},
      \ {"word":  "\\Vvdash",              "menu":  "⊪ "},
      \ {"word":  "\\wedge",               "menu":  "∧"},
      \ {"word":  "\\wp",                  "menu":  "℘ "},
      \ {"word":  "\\wr",                  "menu":  "≀"},
      \ {"word":  "\\xi",                  "menu":  "ξ "},
      \ {"word":  "\\Xi",                  "menu":  "Ξ "},
      \ {"word":  "\\zeta",                "menu":  "ζ "} ]
